version: '2'

services:
  api-gw:
    build: 
      context: .
      dockerfile: ./packages/api-gw/Dockerfile
      args:
        - PORT=$API_SERVER_PORT
    depends_on:
      - db
    ports:
      - "8081:8081"
    container_name: api-gw
    restart: unless-stopped
    links:
      - db
    networks:
      - skilly-network
    volumes:
      - ".env:/src/.env"

  web-ui:
    build:
      context: .
      dockerfile: ./packages/web-ui/Dockerfile
      args:
        - PORT=$WEB_SERVER_PORT
    depends_on:
      - api-gw
    ports:
      - "3000:3000"
    container_name: web-ui
    restart: unless-stopped
    links:
      - api-gw
    networks:
      - skilly-network
    volumes:
      - ".env:/src/app/packages/web-ui/.env"

  db:
    image: mongo
    container_name: db
    restart: unless-stopped
    command: [--auth]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_ADMIN_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_ADMIN_PASS
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - skilly-network

networks:
  skilly-network:
    driver: bridge
